### ISSUE TITLE
Menü + Überschrift - Änderungsvorschläge

### ISSUE THREAD

**Issue by Hoangi** [pandaaan/kumoon#12]
Ein paar Vorschläge für Einfachheit (muss du nicht übernehmen)

-In den Überschriften statt Part einfach "02 - The Concept"?
-eventuell das "Chapter" in den Unterpunkten für rauslassen?
-Menü bereits ausgeklappt ohne, dass man es erst aufklappen muss? Oder direkt ohne aufklappbar funktion? Da das Menü eh schon wenige Punkte hat wird es nicht unübersichtlicht wenn es schon aufgeklappt ist.

_Originally posted by @Hoangi in https://github.com/pandaaan/kumoon/issues/4#issuecomment-723668231_

**Comment by pandaaan** [comment]
menu habe ich extra so gemacht, weil ich es nicht hinbekommen habe den content zu verschieben xD 
das war mir zu zeit aufwendig. Die sidebar liegt nämlich über den text wenn er offen ist. ich kann morgen da nochmal schauen wenn ich zeit habe

**Comment by Hoangi** [comment]
Ah meinte nicht, dass die Sidebar offen ist, sondern die Unterpunkte zu den Überschriften. Aber war wie gesagt nur eine Kleinigkeit :D
