### ISSUE TITLE
Extra (lmao)

### ISSUE THREAD

**Issue by Hoangi** [pandaaan/kumoon#6]
![grafik](https://user-images.githubusercontent.com/74110281/98448793-1128d400-212f-11eb-9146-16f4c0e25048.png)

"omg dats me" I said and then I get hit by my teammates for thinking of giving up.

**Comment by pandaaan** [comment]
:smiling_imp:

**Comment by hubui** [comment]
ist doch witzig, kann man einbringen, falls wirs schaffen .. xD
